import type { Clip, StyleGuideArtifacts, StyleRule, TastePattern } from "../../drizzle/schema";

/**
 * Compile a versioned StyleLab artifact set from active rules + supporting evidence.
 * Pure / deterministic — easy to unit test.
 */
export function compileStyleGuide(args: {
  ownerName: string;
  rules: StyleRule[];
  patterns: TastePattern[];
  citedClips: Clip[];
}): StyleGuideArtifacts {
  const { ownerName, rules, patterns, citedClips } = args;
  const clipMap = new Map(citedClips.map((c) => [c.id, c]));

  const styleGuideMd = renderStyleGuide(ownerName, rules, patterns, clipMap);
  const skillMd = renderSkillMd(ownerName, rules);
  const styleProfileJson = JSON.stringify(
    {
      owner: ownerName,
      generatedAt: new Date().toISOString(),
      patterns: patterns.map((p) => ({
        id: p.id,
        title: p.title,
        description: p.description,
        evidenceClipIds: p.evidenceClipIds ?? [],
      })),
      rules: rules.map((r) => ({
        id: r.id,
        title: r.title,
        positiveInstruction: r.positiveInstruction,
        avoidanceGuidance: r.avoidanceGuidance,
        revisionGuidance: r.revisionGuidance,
        citationClipIds: r.citationClipIds ?? [],
      })),
    },
    null,
    2
  );
  const claudeInstructions = renderAssistantInstructions("Claude", ownerName, rules);
  const chatgptInstructions = renderAssistantInstructions("ChatGPT", ownerName, rules);

  return { styleGuideMd, skillMd, styleProfileJson, claudeInstructions, chatgptInstructions };
}

function renderStyleGuide(
  owner: string,
  rules: StyleRule[],
  patterns: TastePattern[],
  clips: Map<number, Clip>
): string {
  const lines: string[] = [];
  lines.push(`# ${owner}'s Style Guide`);
  lines.push("");
  lines.push(`> Generated by StyleLab on ${new Date().toLocaleDateString()}.`);
  lines.push("");
  lines.push("## Voice in one paragraph");
  lines.push("");
  lines.push(synthesizeVoiceParagraph(rules, patterns));
  lines.push("");
  if (patterns.length) {
    lines.push("## Recurring patterns");
    lines.push("");
    for (const p of patterns) {
      lines.push(`### ${p.title}`);
      lines.push("");
      lines.push(p.description);
      lines.push("");
    }
  }
  lines.push("## Rules");
  lines.push("");
  if (rules.length === 0) {
    lines.push("_No active rules yet. Generate some from your taste patterns._");
    lines.push("");
  }
  for (const r of rules) {
    lines.push(`### ${r.title}`);
    lines.push("");
    lines.push(`**Do:** ${r.positiveInstruction}`);
    lines.push("");
    lines.push(`**Avoid:** ${r.avoidanceGuidance}`);
    lines.push("");
    lines.push(`**When revising:** ${r.revisionGuidance}`);
    lines.push("");
    const cites = (r.citationClipIds ?? []).map((id) => clips.get(id)).filter(Boolean) as Clip[];
    if (cites.length) {
      lines.push("**Evidence:**");
      lines.push("");
      for (const c of cites) {
        const attribution = [c.sourceAuthor, c.sourceTitle].filter(Boolean).join(", ");
        lines.push(`> ${truncate(c.content, 320)}${attribution ? `  \n> — ${attribution}` : ""}`);
        lines.push("");
      }
    }
  }
  return lines.join("\n").trimEnd() + "\n";
}

function renderSkillMd(owner: string, rules: StyleRule[]): string {
  const lines: string[] = [];
  lines.push("---");
  lines.push(`name: ${owner.toLowerCase().replace(/\s+/g, "-")}-writing-style`);
  lines.push(`description: Use this skill to write or revise text in ${owner}'s personal voice. It encodes ${owner}'s taste in tone, syntax, imagery, rhythm, and rhetorical moves, distilled from passages they admire.`);
  lines.push("---");
  lines.push("");
  lines.push(`# ${owner}'s Writing Style Skill`);
  lines.push("");
  lines.push("## When to use");
  lines.push("");
  lines.push("Apply when drafting or revising essays, posts, threads, captions, or notes that should sound like the user. When in doubt, prefer compression over completeness and implication over explanation.");
  lines.push("");
  lines.push("## Rules");
  lines.push("");
  for (const r of rules) {
    lines.push(`- **${r.title}** — Do: ${r.positiveInstruction} Avoid: ${r.avoidanceGuidance} Revise: ${r.revisionGuidance}`);
  }
  if (!rules.length) lines.push("- _(No rules yet — generate from taste patterns.)_");
  lines.push("");
  lines.push("## Output protocol");
  lines.push("");
  lines.push("1. Read the request and the rules above.");
  lines.push("2. Draft using the rules. When a sentence violates a rule, revise it before output.");
  lines.push("3. End with one sentence flagging which rules guided the most edits.");
  lines.push("");
  return lines.join("\n");
}

function renderAssistantInstructions(assistant: string, owner: string, rules: StyleRule[]): string {
  const lines: string[] = [];
  lines.push(`# ${assistant} custom instructions for ${owner}`);
  lines.push("");
  lines.push(`When writing or editing for ${owner}, follow these rules. Treat them as constraints, not suggestions.`);
  lines.push("");
  for (const r of rules) {
    lines.push(`- ${r.title}: ${r.positiveInstruction} Avoid ${lower(r.avoidanceGuidance)}`);
  }
  if (!rules.length) lines.push("- (Rules not yet generated.)");
  lines.push("");
  lines.push("Tone defaults: clear, specific, restrained. Prefer short sentences when the idea is hot, longer sentences when the idea is being unfolded. End with the strongest concrete image you have.");
  return lines.join("\n");
}

function synthesizeVoiceParagraph(rules: StyleRule[], patterns: TastePattern[]): string {
  if (!rules.length && !patterns.length) {
    return "Your voice profile is empty. Capture clips, reflect on them, and generate patterns to populate this section.";
  }
  const phrases: string[] = [];
  if (patterns.length) {
    phrases.push(`Recurring strengths: ${patterns.slice(0, 3).map((p) => p.title.toLowerCase()).join("; ")}`);
  }
  if (rules.length) {
    phrases.push(`Active rules emphasize ${rules.slice(0, 3).map((r) => lower(r.title)).join(", ")}`);
  }
  return `${phrases.join(". ")}.`;
}

function lower(s: string) {
  return s ? s[0].toLowerCase() + s.slice(1) : s;
}

function truncate(s: string, n: number) {
  if (s.length <= n) return s;
  return s.slice(0, n - 1).trimEnd() + "…";
}
